---
title: Ik heb wat wijzigingen aangebracht, maar die zijn verdwenen
hero_image: images/banner.png
description: Ik heb wat wijzigingen aangebracht, maar die zijn verdwenen
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - title: Ik heb wat wijzigingen aangebracht, maar die zijn verdwenen
